# Generated by Django 5.1.7 on 2025-05-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiffinServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service Provider Name')),
                ('owner_name', models.CharField(max_length=150, verbose_name='Owner Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('operating_city_area', models.CharField(help_text='e.g., Mumbai - Andheri, Pune - Kothrud', max_length=255, verbose_name='Operating City/Area')),
                ('meal_type_offered', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('BOTH', 'Both Veg & Non-Veg')], default='VEG', max_length=10, verbose_name='Type of Meal Offered')),
                ('delivery_options', models.TextField(help_text='e.g., Free delivery within 5km, Chargeable beyond, Specific timings', verbose_name='Delivery Options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tiffin Service Provider',
                'verbose_name_plural': 'Tiffin Service Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200, verbose_name='Package Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BOTH', 'Both Lunch & Dinner')], default='LUNCH', max_length=10, verbose_name='Meal Type (Lunch/Dinner)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10, verbose_name='Duration')),
                ('service_area_city', models.CharField(help_text='e.g., Mumbai - Andheri West. Be specific for filtering.', max_length=255, verbose_name='Area/City of Service for this Package')),
                ('image', models.ImageField(blank=True, help_text='Optional: A representative image of the meal package.', null=True, upload_to='meal_package_images/', verbose_name='Package Image')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this package from public view.', verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tiffin_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_packages', to='tiffin_app.tiffinserviceprovider', verbose_name='Associated Tiffin Service')),
            ],
            options={
                'verbose_name': 'Meal Package',
                'verbose_name_plural': 'Meal Packages',
                'ordering': ['-created_at', 'package_name'],
            },
        ),
    ]
